/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : IO_Map.h
**     Project     : ProcessorExpert
**     Processor   : MCF51CN128CGT
**     Component   : IO_Map
**     Version     : Driver 01.00
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2012-09-27, 07:41, # CodeGen: 0
**     Abstract    :
**         IO_Map.h - implements an IO device's mapping. 
**         This module contains symbol definitions of all peripheral 
**         registers and bits. 
**     Settings    :
**
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef _IO_MAP_H
#define _IO_MAP_H
/* Based on CPU DB MCF51CN128_48, version 3.00.031 (RegistersPrg V2.33) */
/* DataSheet : MCF51CN128RM Rev. 4 January 2009 */

#include <stdint.h>

/**************** registers I/O map ****************/

/*** NVFTRIM - Nonvolatile MCG Fine Trim; 0x000003FE ***/
#define NVFTRIM 0x000003FE
#define NVFTRIM_FTRIM                   0x01U


/*** NVMCGTRM - Nonvolatile MCG Trim Register; 0x000003FF ***/

#define NVMCGTRM  0x000003FF
#define NVMCGTRM_TRIM0                  0x01U
#define NVMCGTRM_TRIM1                  0x02U
#define NVMCGTRM_TRIM2                  0x04U
#define NVMCGTRM_TRIM3                  0x08U
#define NVMCGTRM_TRIM4                  0x10U
#define NVMCGTRM_TRIM5                  0x20U
#define NVMCGTRM_TRIM6                  0x40U
#define NVMCGTRM_TRIM7                  0x80U


/*** NVBACKKEY0 - Backdoor Comparison Key 0; 0x00000400 ***/
#define NVBACKKEY0 0x00000400
#define NVBACKKEY0_KEY0                 0x01U
#define NVBACKKEY0_KEY1                 0x02U
#define NVBACKKEY0_KEY2                 0x04U
#define NVBACKKEY0_KEY3                 0x08U
#define NVBACKKEY0_KEY4                 0x10U
#define NVBACKKEY0_KEY5                 0x20U
#define NVBACKKEY0_KEY6                 0x40U
#define NVBACKKEY0_KEY7                 0x80U


/*** NVBACKKEY1 - Backdoor Comparison Key 1; 0x00000401 ***/
#define NVBACKKEY1 0x00000401
#define NVBACKKEY1_KEY0                 0x01U
#define NVBACKKEY1_KEY1                 0x02U
#define NVBACKKEY1_KEY2                 0x04U
#define NVBACKKEY1_KEY3                 0x08U
#define NVBACKKEY1_KEY4                 0x10U
#define NVBACKKEY1_KEY5                 0x20U
#define NVBACKKEY1_KEY6                 0x40U
#define NVBACKKEY1_KEY7                 0x80U


/*** NVBACKKEY2 - Backdoor Comparison Key 2; 0x00000402 ***/
#define NVBACKKEY2 0x00000402
#define NVBACKKEY2_KEY0                 0x01U
#define NVBACKKEY2_KEY1                 0x02U
#define NVBACKKEY2_KEY2                 0x04U
#define NVBACKKEY2_KEY3                 0x08U
#define NVBACKKEY2_KEY4                 0x10U
#define NVBACKKEY2_KEY5                 0x20U
#define NVBACKKEY2_KEY6                 0x40U
#define NVBACKKEY2_KEY7                 0x80U


/*** NVBACKKEY3 - Backdoor Comparison Key 3; 0x00000403 ***/
#define NVBACKKEY3 0x00000403
#define NVBACKKEY3_KEY0                 0x01U
#define NVBACKKEY3_KEY1                 0x02U
#define NVBACKKEY3_KEY2                 0x04U
#define NVBACKKEY3_KEY3                 0x08U
#define NVBACKKEY3_KEY4                 0x10U
#define NVBACKKEY3_KEY5                 0x20U
#define NVBACKKEY3_KEY6                 0x40U
#define NVBACKKEY3_KEY7                 0x80U


/*** NVBACKKEY4 - Backdoor Comparison Key 4; 0x00000404 ***/
#define NVBACKKEY4 0x00000404
#define NVBACKKEY4_KEY0                 0x01U
#define NVBACKKEY4_KEY1                 0x02U
#define NVBACKKEY4_KEY2                 0x04U
#define NVBACKKEY4_KEY3                 0x08U
#define NVBACKKEY4_KEY4                 0x10U
#define NVBACKKEY4_KEY5                 0x20U
#define NVBACKKEY4_KEY6                 0x40U
#define NVBACKKEY4_KEY7                 0x80U


/*** NVBACKKEY5 - Backdoor Comparison Key 5; 0x00000405 ***/
#define NVBACKKEY5 0x00000405
#define NVBACKKEY5_KEY0                 0x01U
#define NVBACKKEY5_KEY1                 0x02U
#define NVBACKKEY5_KEY2                 0x04U
#define NVBACKKEY5_KEY3                 0x08U
#define NVBACKKEY5_KEY4                 0x10U
#define NVBACKKEY5_KEY5                 0x20U
#define NVBACKKEY5_KEY6                 0x40U
#define NVBACKKEY5_KEY7                 0x80U


/*** NVBACKKEY6 - Backdoor Comparison Key 6; 0x00000406 ***/
#define _NVBACKKEY6 0x00000406
#define NVBACKKEY6_KEY0                 0x01U
#define NVBACKKEY6_KEY1                 0x02U
#define NVBACKKEY6_KEY2                 0x04U
#define NVBACKKEY6_KEY3                 0x08U
#define NVBACKKEY6_KEY4                 0x10U
#define NVBACKKEY6_KEY5                 0x20U
#define NVBACKKEY6_KEY6                 0x40U
#define NVBACKKEY6_KEY7                 0x80U


/*** NVBACKKEY7 - Backdoor Comparison Key 7; 0x00000407 ***/
#define NVBACKKEY7 0x00000407
#define NVBACKKEY7_KEY0                 0x01U
#define NVBACKKEY7_KEY1                 0x02U
#define NVBACKKEY7_KEY2                 0x04U
#define NVBACKKEY7_KEY3                 0x08U
#define NVBACKKEY7_KEY4                 0x10U
#define NVBACKKEY7_KEY5                 0x20U
#define NVBACKKEY7_KEY6                 0x40U
#define NVBACKKEY7_KEY7                 0x80U


/*** NVPROT - Nonvolatile Flash Protection Register; 0x0000040D ***/
#define NVPROT 0x0000040D
#define NVPROT_FPOPEN                   0x01U
#define NVPROT_FPS0                     0x02U
#define NVPROT_FPS1                     0x04U
#define NVPROT_FPS2                     0x08U
#define NVPROT_FPS3                     0x10U
#define NVPROT_FPS4                     0x20U
#define NVPROT_FPS5                     0x40U
#define NVPROT_FPS6                     0x80U
#define NVPROT_FPS                      0xFEU
#define NVPROT_FPS_BITNUM               0x01U


/*** NVOPT - Nonvolatile Flash Options Register; 0x0000040F ***/
#define NVOPT 0x0000040F
#define NVOPT_SEC0                      0x01U
#define NVOPT_SEC1                      0x02U
#define NVOPT_KEYEN0                    0x40U
#define NVOPT_KEYEN1                    0x80U
#define NVOPT_SEC                       0x03U
#define NVOPT_SEC_BITNUM                0x00U
#define NVOPT_KEYEN                     0xC0U
#define NVOPT_KEYEN_BITNUM              0x06U


/*** RGPIO_DIR - RGPIO Data Direction Register; 0x00C00000 ***/
#define RGPIO_DIR (*(volatile uint16_t*)(0x00C00000))
#define RGPIO_DIR_DIR0                  0x01U
#define RGPIO_DIR_DIR1                  0x02U
#define RGPIO_DIR_DIR2                  0x04U
#define RGPIO_DIR_DIR3                  0x08U
#define RGPIO_DIR_DIR4                  0x10U
#define RGPIO_DIR_DIR5                  0x20U
#define RGPIO_DIR_DIR6                  0x40U
#define RGPIO_DIR_DIR7                  0x80U
#define RGPIO_DIR_DIR8                  0x0100U
#define RGPIO_DIR_DIR9                  0x0200U
#define RGPIO_DIR_DIR10                 0x0400U
#define RGPIO_DIR_DIR11                 0x0800U
#define RGPIO_DIR_DIR12                 0x1000U
#define RGPIO_DIR_DIR13                 0x2000U
#define RGPIO_DIR_DIR14                 0x4000U
#define RGPIO_DIR_DIR15                 0x8000U


/*** RGPIO_DATA - RGPIO Data Register; 0x00C00002 ***/
#define RGPIO_DATA (*(volatile uint16_t*)(0x00C00002))

#define RGPIO_DATA_DATA0                0x01U
#define RGPIO_DATA_DATA1                0x02U
#define RGPIO_DATA_DATA2                0x04U
#define RGPIO_DATA_DATA3                0x08U
#define RGPIO_DATA_DATA4                0x10U
#define RGPIO_DATA_DATA5                0x20U
#define RGPIO_DATA_DATA6                0x40U
#define RGPIO_DATA_DATA7                0x80U
#define RGPIO_DATA_DATA8                0x0100U
#define RGPIO_DATA_DATA9                0x0200U
#define RGPIO_DATA_DATA10               0x0400U
#define RGPIO_DATA_DATA11               0x0800U
#define RGPIO_DATA_DATA12               0x1000U
#define RGPIO_DATA_DATA13               0x2000U
#define RGPIO_DATA_DATA14               0x4000U
#define RGPIO_DATA_DATA15               0x8000U


/*** RGPIO_ENB - RGPIO Pin Enable Register; 0x00C00004 ***/
#define RGPIO_ENB (*(volatile uint16_t*)(0x00C00004))
#define RGPIO_ENB_ENB0                  0x01U
#define RGPIO_ENB_ENB1                  0x02U
#define RGPIO_ENB_ENB2                  0x04U
#define RGPIO_ENB_ENB3                  0x08U
#define RGPIO_ENB_ENB4                  0x10U
#define RGPIO_ENB_ENB5                  0x20U
#define RGPIO_ENB_ENB6                  0x40U
#define RGPIO_ENB_ENB7                  0x80U
#define RGPIO_ENB_ENB8                  0x0100U
#define RGPIO_ENB_ENB9                  0x0200U
#define RGPIO_ENB_ENB10                 0x0400U
#define RGPIO_ENB_ENB11                 0x0800U
#define RGPIO_ENB_ENB12                 0x1000U
#define RGPIO_ENB_ENB13                 0x2000U
#define RGPIO_ENB_ENB14                 0x4000U
#define RGPIO_ENB_ENB15                 0x8000U


/*** RGPIO_CLR - RGPIO Clear Data Register; 0x00C00006 ***/
#define RGPIO_CLR (*(volatile uint16_t*)(0x00C00006))
#define RGPIO_CLR_CLR0                  0x01U
#define RGPIO_CLR_CLR1                  0x02U
#define RGPIO_CLR_CLR2                  0x04U
#define RGPIO_CLR_CLR3                  0x08U
#define RGPIO_CLR_CLR4                  0x10U
#define RGPIO_CLR_CLR5                  0x20U
#define RGPIO_CLR_CLR6                  0x40U
#define RGPIO_CLR_CLR7                  0x80U
#define RGPIO_CLR_CLR8                  0x0100U
#define RGPIO_CLR_CLR9                  0x0200U
#define RGPIO_CLR_CLR10                 0x0400U
#define RGPIO_CLR_CLR11                 0x0800U
#define RGPIO_CLR_CLR12                 0x1000U
#define RGPIO_CLR_CLR13                 0x2000U
#define RGPIO_CLR_CLR14                 0x4000U
#define RGPIO_CLR_CLR15                 0x8000U


/*** RGPIO_SET - RGPIO Set Data Register; 0x00C0000A ***/
#define RGPIO_SET (*(volatile uint16_t*)(0x00C0000A))

#define RGPIO_SET_SET0                  0x01U
#define RGPIO_SET_SET1                  0x02U
#define RGPIO_SET_SET2                  0x04U
#define RGPIO_SET_SET3                  0x08U
#define RGPIO_SET_SET4                  0x10U
#define RGPIO_SET_SET5                  0x20U
#define RGPIO_SET_SET6                  0x40U
#define RGPIO_SET_SET7                  0x80U
#define RGPIO_SET_SET8                  0x0100U
#define RGPIO_SET_SET9                  0x0200U
#define RGPIO_SET_SET10                 0x0400U
#define RGPIO_SET_SET11                 0x0800U
#define RGPIO_SET_SET12                 0x1000U
#define RGPIO_SET_SET13                 0x2000U
#define RGPIO_SET_SET14                 0x4000U
#define RGPIO_SET_SET15                 0x8000U


/*** RGPIO_TOG - RGPIO Toggle Data Register; 0x00C0000E ***/
#define RGPIO_TOG (*(volatile uint16_t*)(0x00C0000E))
#define RGPIO_TOG_TOG0                  0x01U
#define RGPIO_TOG_TOG1                  0x02U
#define RGPIO_TOG_TOG2                  0x04U
#define RGPIO_TOG_TOG3                  0x08U
#define RGPIO_TOG_TOG4                  0x10U
#define RGPIO_TOG_TOG5                  0x20U
#define RGPIO_TOG_TOG6                  0x40U
#define RGPIO_TOG_TOG7                  0x80U
#define RGPIO_TOG_TOG8                  0x0100U
#define RGPIO_TOG_TOG9                  0x0200U
#define RGPIO_TOG_TOG10                 0x0400U
#define RGPIO_TOG_TOG11                 0x0800U
#define RGPIO_TOG_TOG12                 0x1000U
#define RGPIO_TOG_TOG13                 0x2000U
#define RGPIO_TOG_TOG14                 0x4000U
#define RGPIO_TOG_TOG15                 0x8000U


/*** PTAD - Port A Data Register; 0xFFFF8000 ***/
#define PTAD (*(volatile uint8_t*)(0xFFFF8000))
#define PTAD_PTAD0                      0x01U
#define PTAD_PTAD1                      0x02U
#define PTAD_PTAD2                      0x04U
#define PTAD_PTAD3                      0x08U
#define PTAD_PTAD4                      0x10U
#define PTAD_PTAD5                      0x20U
#define PTAD_PTAD6                      0x40U
#define PTAD_PTAD7                      0x80U


/*** PTADD - Port A Data Direction Register; 0xFFFF8001 ***/
#define PTADD (*(volatile uint8_t*)(0xFFFF8001))
#define PTADD_PTADD0                    0x01U
#define PTADD_PTADD1                    0x02U
#define PTADD_PTADD2                    0x04U
#define PTADD_PTADD3                    0x08U
#define PTADD_PTADD4                    0x10U
#define PTADD_PTADD5                    0x20U
#define PTADD_PTADD6                    0x40U
#define PTADD_PTADD7                    0x80U


/*** PTAPE - Port A Pull Enable Register; 0xFFFF8008 ***/
#define PTAPE (*(volatile uint8_t*)(0xFFFF8008))
#define PTAPE_PTAPE0                    0x01U
#define PTAPE_PTAPE1                    0x02U
#define PTAPE_PTAPE2                    0x04U
#define PTAPE_PTAPE3                    0x08U
#define PTAPE_PTAPE4                    0x10U
#define PTAPE_PTAPE5                    0x20U
#define PTAPE_PTAPE6                    0x40U
#define PTAPE_PTAPE7                    0x80U


/*** PTASE - Port A Slew Rate Enable Register; 0xFFFF8009 ***/
#define PTASE (*(volatile uint8_t*)(0xFFFF8009))
#define PTASE_PTASE0                    0x01U
#define PTASE_PTASE1                    0x02U
#define PTASE_PTASE2                    0x04U
#define PTASE_PTASE3                    0x08U
#define PTASE_PTASE4                    0x10U
#define PTASE_PTASE5                    0x20U
#define PTASE_PTASE6                    0x40U
#define PTASE_PTASE7                    0x80U


/*** PTADS - Port A Drive Strength Selection Register; 0xFFFF800A ***/
#define PTADS (*(volatile uint8_t*)(0xFFFF800A))
#define PTADS_PTADS0                    0x01U
#define PTADS_PTADS1                    0x02U
#define PTADS_PTADS2                    0x04U
#define PTADS_PTADS3                    0x08U
#define PTADS_PTADS4                    0x10U
#define PTADS_PTADS5                    0x20U
#define PTADS_PTADS6                    0x40U
#define PTADS_PTADS7                    0x80U


/*** PTAIFE - Port A Input Filter Enable Register; 0xFFFF800B ***/
#define PTAIFE (*(volatile uint8_t*)(0xFFFF800B))
#define PTAIFE_PTAIFE0                  0x01U
#define PTAIFE_PTAIFE1                  0x02U
#define PTAIFE_PTAIFE2                  0x04U
#define PTAIFE_PTAIFE3                  0x08U
#define PTAIFE_PTAIFE4                  0x10U
#define PTAIFE_PTAIFE5                  0x20U
#define PTAIFE_PTAIFE6                  0x40U
#define PTAIFE_PTAIFE7                  0x80U


/*** PTBD - Port B Data Register; 0xFFFF8010 ***/
#define PTBD (*(volatile uint8_t*)(0xFFFF8010))
#define PTBD_PTBD0                      0x01U
#define PTBD_PTBD1                      0x02U
#define PTBD_PTBD2                      0x04U
#define PTBD_PTBD3                      0x08U
#define PTBD_PTBD4                      0x10U
#define PTBD_PTBD5                      0x20U
#define PTBD_PTBD6                      0x40U
#define PTBD_PTBD7                      0x80U


/*** PTBDD - Port B Data Direction Register; 0xFFFF8011 ***/
#define PTBDD (*(volatile uint8_t*)(0xFFFF8011))
#define PTBDD_PTBDD0                    0x01U
#define PTBDD_PTBDD1                    0x02U
#define PTBDD_PTBDD2                    0x04U
#define PTBDD_PTBDD3                    0x08U
#define PTBDD_PTBDD4                    0x10U
#define PTBDD_PTBDD5                    0x20U
#define PTBDD_PTBDD6                    0x40U
#define PTBDD_PTBDD7                    0x80U


/*** PTBPE - Port B Pull Enable Register; 0xFFFF8018 ***/
#define PTBPE (*(volatile uint8_t*)(0xFFFF8018))
#define PTBPE_PTBPE0                    0x01U
#define PTBPE_PTBPE1                    0x02U
#define PTBPE_PTBPE2                    0x04U
#define PTBPE_PTBPE3                    0x08U
#define PTBPE_PTBPE4                    0x10U
#define PTBPE_PTBPE5                    0x20U
#define PTBPE_PTBPE6                    0x40U
#define PTBPE_PTBPE7                    0x80U


/*** PTBSE - Port B Slew Rate Enable Register; 0xFFFF8019 ***/
#define PTBSE (*(volatile uint8_t*)(0xFFFF8019))
#define PTBSE_PTBSE0                    0x01U
#define PTBSE_PTBSE1                    0x02U
#define PTBSE_PTBSE2                    0x04U
#define PTBSE_PTBSE3                    0x08U
#define PTBSE_PTBSE4                    0x10U
#define PTBSE_PTBSE5                    0x20U
#define PTBSE_PTBSE6                    0x40U
#define PTBSE_PTBSE7                    0x80U


/*** PTBDS - Port B Drive Strength Selection Register; 0xFFFF801A ***/
#define PTBDS (*(volatile uint8_t*)(0xFFFF801A))
#define PTBDS_PTBDS0                    0x01U
#define PTBDS_PTBDS1                    0x02U
#define PTBDS_PTBDS2                    0x04U
#define PTBDS_PTBDS3                    0x08U
#define PTBDS_PTBDS4                    0x10U
#define PTBDS_PTBDS5                    0x20U
#define PTBDS_PTBDS6                    0x40U
#define PTBDS_PTBDS7                    0x80U


/*** PTBIFE - Port B Input Filter Enable Register; 0xFFFF801B ***/
#define PTBIFE (*(volatile uint8_t*)(0xFFFF801B))
#define PTBIFE_PTBIFE0                  0x01U
#define PTBIFE_PTBIFE1                  0x02U
#define PTBIFE_PTBIFE2                  0x04U
#define PTBIFE_PTBIFE3                  0x08U
#define PTBIFE_PTBIFE4                  0x10U
#define PTBIFE_PTBIFE5                  0x20U
#define PTBIFE_PTBIFE6                  0x40U
#define PTBIFE_PTBIFE7                  0x80U


/*** PTCD - Port C Data Register; 0xFFFF8020 ***/
#define PTCD (*(volatile uint8_t*)(0xFFFF8020))
#define PTCD_PTCD0                      0x01U
#define PTCD_PTCD1                      0x02U
#define PTCD_PTCD2                      0x04U
#define PTCD_PTCD3                      0x08U
#define PTCD_PTCD4                      0x10U
#define PTCD_PTCD5                      0x20U
#define PTCD_PTCD6                      0x40U
#define PTCD_PTCD7                      0x80U


/*** PTCDD - Port C Data Direction Register; 0xFFFF8021 ***/
#define PTCDD (*(volatile uint8_t*)(0xFFFF8021))
#define PTCDD_PTCDD0                    0x01U
#define PTCDD_PTCDD1                    0x02U
#define PTCDD_PTCDD2                    0x04U
#define PTCDD_PTCDD3                    0x08U
#define PTCDD_PTCDD4                    0x10U
#define PTCDD_PTCDD5                    0x20U
#define PTCDD_PTCDD6                    0x40U
#define PTCDD_PTCDD7                    0x80U


/*** PTCPE - Port C Pull Enable Register; 0xFFFF8028 ***/
#define PTCPE (*(volatile uint8_t*)(0xFFFF8028))
#define PTCPE_PTCPE0                    0x01U
#define PTCPE_PTCPE1                    0x02U
#define PTCPE_PTCPE2                    0x04U
#define PTCPE_PTCPE3                    0x08U
#define PTCPE_PTCPE4                    0x10U
#define PTCPE_PTCPE5                    0x20U
#define PTCPE_PTCPE6                    0x40U
#define PTCPE_PTCPE7                    0x80U


/*** PTCSE - Port C Slew Rate Enable Register; 0xFFFF8029 ***/
#define PTCSE (*(volatile uint8_t*)(0xFFFF8029))
#define PTCSE_PTCSE0                    0x01U
#define PTCSE_PTCSE1                    0x02U
#define PTCSE_PTCSE2                    0x04U
#define PTCSE_PTCSE3                    0x08U
#define PTCSE_PTCSE4                    0x10U
#define PTCSE_PTCSE5                    0x20U
#define PTCSE_PTCSE6                    0x40U
#define PTCSE_PTCSE7                    0x80U


/*** PTCDS - Port C Drive Strength Selection Register; 0xFFFF802A ***/
#define PTCDS (*(volatile uint8_t*)(0xFFFF802A))
#define PTCDS_PTCDS0                    0x01U
#define PTCDS_PTCDS1                    0x02U
#define PTCDS_PTCDS2                    0x04U
#define PTCDS_PTCDS3                    0x08U
#define PTCDS_PTCDS4                    0x10U
#define PTCDS_PTCDS5                    0x20U
#define PTCDS_PTCDS6                    0x40U
#define PTCDS_PTCDS7                    0x80U


/*** PTCIFE - Port C Input Filter Enable Register; 0xFFFF802B ***/
#define PTCIFE (*(volatile uint8_t*)(0xFFFF802B))
#define PTCIFE_PTCIFE0                  0x01U
#define PTCIFE_PTCIFE1                  0x02U
#define PTCIFE_PTCIFE2                  0x04U
#define PTCIFE_PTCIFE3                  0x08U
#define PTCIFE_PTCIFE4                  0x10U
#define PTCIFE_PTCIFE5                  0x20U
#define PTCIFE_PTCIFE6                  0x40U
#define PTCIFE_PTCIFE7                  0x80U


/*** PTDD - Port D Data Register; 0xFFFF8030 ***/
#define PTDD (*(volatile uint8_t*)(0xFFFF8030))
#define PTDD_PTDD0                      0x01U
#define PTDD_PTDD1                      0x02U
#define PTDD_PTDD2                      0x04U
#define PTDD_PTDD3                      0x08U
#define PTDD_PTDD4                      0x10U
#define PTDD_PTDD5                      0x20U
#define PTDD_PTDD6                      0x40U
#define PTDD_PTDD7                      0x80U


/*** PTDDD - Port D Data Direction Register; 0xFFFF8031 ***/
#define PTDDD (*(volatile uint8_t*)(0xFFFF8031))
#define PTDDD_PTDDD0                    0x01U
#define PTDDD_PTDDD1                    0x02U
#define PTDDD_PTDDD2                    0x04U
#define PTDDD_PTDDD3                    0x08U
#define PTDDD_PTDDD4                    0x10U
#define PTDDD_PTDDD5                    0x20U
#define PTDDD_PTDDD6                    0x40U
#define PTDDD_PTDDD7                    0x80U


/*** PTDPE - Port D Pull Enable Register; 0xFFFF8038 ***/
#define PTDPE (*(volatile uint8_t*)(0xFFFF8038))
#define PTDPE_PTDPE0                    0x01U
#define PTDPE_PTDPE1                    0x02U
#define PTDPE_PTDPE2                    0x04U
#define PTDPE_PTDPE3                    0x08U
#define PTDPE_PTDPE4                    0x10U
#define PTDPE_PTDPE5                    0x20U
#define PTDPE_PTDPE6                    0x40U
#define PTDPE_PTDPE7                    0x80U


/*** PTDSE - Port D Slew Rate Enable Register; 0xFFFF8039 ***/
#define PTDSE (*(volatile uint8_t*)(0xFFFF8039))
#define PTDSE_PTDSE0                    0x01U
#define PTDSE_PTDSE1                    0x02U
#define PTDSE_PTDSE2                    0x04U
#define PTDSE_PTDSE3                    0x08U
#define PTDSE_PTDSE4                    0x10U
#define PTDSE_PTDSE5                    0x20U
#define PTDSE_PTDSE6                    0x40U
#define PTDSE_PTDSE7                    0x80U


/*** PTDDS - Port D Drive Strength Selection Register; 0xFFFF803A ***/
#define PTDDS (*(volatile uint8_t*)(0xFFFF803A))
#define PTDDS_PTDDS0                    0x01U
#define PTDDS_PTDDS1                    0x02U
#define PTDDS_PTDDS2                    0x04U
#define PTDDS_PTDDS3                    0x08U
#define PTDDS_PTDDS4                    0x10U
#define PTDDS_PTDDS5                    0x20U
#define PTDDS_PTDDS6                    0x40U
#define PTDDS_PTDDS7                    0x80U


/*** PTDIFE - Port D Input Filter Enable Register; 0xFFFF803B ***/
#define PTDIFE (*(volatile uint8_t*)(0xFFFF803B))
#define PTDIFE_PTDIFE0                  0x01U
#define PTDIFE_PTDIFE1                  0x02U
#define PTDIFE_PTDIFE2                  0x04U
#define PTDIFE_PTDIFE3                  0x08U
#define PTDIFE_PTDIFE4                  0x10U
#define PTDIFE_PTDIFE5                  0x20U
#define PTDIFE_PTDIFE6                  0x40U
#define PTDIFE_PTDIFE7                  0x80U


/*** PTED - Port E Data Register; 0xFFFF8040 ***/
#define PTED (*(volatile uint8_t*)(0xFFFF8040))
#define PTED_PTED0                      0x01U
#define PTED_PTED1                      0x02U
#define PTED_PTED2                      0x04U
#define PTED_PTED3                      0x08U
#define PTED_PTED4                      0x10U
#define PTED_PTED5                      0x20U
#define PTED_PTED6                      0x40U
#define PTED_PTED7                      0x80U


/*** PTEDD - Port E Data Direction Register; 0xFFFF8041 ***/
#define PTEDD (*(volatile uint8_t*)(0xFFFF8041))
#define PTEDD_PTEDD0                    0x01U
#define PTEDD_PTEDD1                    0x02U
#define PTEDD_PTEDD2                    0x04U
#define PTEDD_PTEDD3                    0x08U
#define PTEDD_PTEDD4                    0x10U
#define PTEDD_PTEDD5                    0x20U
#define PTEDD_PTEDD6                    0x40U
#define PTEDD_PTEDD7                    0x80U


/*** PTEPE - Port E Pull Enable Register; 0xFFFF8048 ***/
#define PTEPE (*(volatile uint8_t*)(0xFFFF8048))
#define PTEPE_PTEPE0                    0x01U
#define PTEPE_PTEPE1                    0x02U
#define PTEPE_PTEPE2                    0x04U
#define PTEPE_PTEPE3                    0x08U
#define PTEPE_PTEPE4                    0x10U
#define PTEPE_PTEPE5                    0x20U
#define PTEPE_PTEPE6                    0x40U
#define PTEPE_PTEPE7                    0x80U


/*** PTESE - Port E Slew Rate Enable Register; 0xFFFF8049 ***/
#define PTESE (*(volatile uint8_t*)(0xFFFF8049))
#define PTESE_PTESE0                    0x01U
#define PTESE_PTESE1                    0x02U
#define PTESE_PTESE2                    0x04U
#define PTESE_PTESE3                    0x08U
#define PTESE_PTESE4                    0x10U
#define PTESE_PTESE5                    0x20U
#define PTESE_PTESE6                    0x40U
#define PTESE_PTESE7                    0x80U


/*** PTEDS - Port E Drive Strength Selection Register; 0xFFFF804A ***/
#define PTEDS (*(volatile uint8_t*)(0xFFFF804A))
#define PTEDS_PTEDS0                    0x01U
#define PTEDS_PTEDS1                    0x02U
#define PTEDS_PTEDS2                    0x04U
#define PTEDS_PTEDS3                    0x08U
#define PTEDS_PTEDS4                    0x10U
#define PTEDS_PTEDS5                    0x20U
#define PTEDS_PTEDS6                    0x40U
#define PTEDS_PTEDS7                    0x80U


/*** PTEIFE - Port E Input Filter Enable Register; 0xFFFF804B ***/
#define PTEIFE (*(volatile uint8_t*)(0xFFFF804B))
#define PTEIFE_PTEIFE0                  0x01U
#define PTEIFE_PTEIFE1                  0x02U
#define PTEIFE_PTEIFE2                  0x04U
#define PTEIFE_PTEIFE3                  0x08U
#define PTEIFE_PTEIFE4                  0x10U
#define PTEIFE_PTEIFE5                  0x20U
#define PTEIFE_PTEIFE6                  0x40U
#define PTEIFE_PTEIFE7                  0x80U


/*** KBI2SC - KBI2 Status and Control Register; 0xFFFF804C ***/

#define KBI2SC (*(volatile uint8_t*)(0xFFFF804C))
#define KBI2SC_KBIMOD                   0x01U
#define KBI2SC_KBIE                     0x02U
#define KBI2SC_KBACK                    0x04U
#define KBI2SC_KBF                      0x08U


/*** KBI2PE - KBI2 Pin Enable Register; 0xFFFF804D ***/
#define KBI2PE (*(volatile uint8_t*)(0xFFFF804D))
#define KBI2PE_KBIPE0                   0x01U
#define KBI2PE_KBIPE1                   0x02U
#define KBI2PE_KBIPE2                   0x04U
#define KBI2PE_KBIPE3                   0x08U
#define KBI2PE_KBIPE4                   0x10U
#define KBI2PE_KBIPE5                   0x20U
#define KBI2PE_KBIPE6                   0x40U
#define KBI2PE_KBIPE7                   0x80U


/*** KBI2ES - KBI2 Edge Select Register; 0xFFFF804E ***/
#define KBI2ES (*(volatile uint8_t*)(0xFFFF804E))
#define KBI2ES_KBEDG0                   0x01U
#define KBI2ES_KBEDG1                   0x02U
#define KBI2ES_KBEDG2                   0x04U
#define KBI2ES_KBEDG3                   0x08U
#define KBI2ES_KBEDG4                   0x10U
#define KBI2ES_KBEDG5                   0x20U
#define KBI2ES_KBEDG6                   0x40U
#define KBI2ES_KBEDG7                   0x80U


/*** PTFD - Port F Data Register; 0xFFFF8050 ***/
#define PTFD (*(volatile uint8_t*)(0xFFFF8050))
#define PTFD_PTFD0                      0x01U
#define PTFD_PTFD1                      0x02U
#define PTFD_PTFD2                      0x04U
#define PTFD_PTFD3                      0x08U
#define PTFD_PTFD4                      0x10U
#define PTFD_PTFD5                      0x20U
#define PTFD_PTFD6                      0x40U
#define PTFD_PTFD7                      0x80U


/*** PTFDD - Port F Data Direction Register; 0xFFFF8051 ***/
#define PTFDD (*(volatile uint8_t*)(0xFFFF8051))
#define PTFDD_PTFDD0                    0x01U
#define PTFDD_PTFDD1                    0x02U
#define PTFDD_PTFDD2                    0x04U
#define PTFDD_PTFDD3                    0x08U
#define PTFDD_PTFDD4                    0x10U
#define PTFDD_PTFDD5                    0x20U
#define PTFDD_PTFDD6                    0x40U
#define PTFDD_PTFDD7                    0x80U


/*** PTFPE - Port F Pull Enable Register; 0xFFFF8058 ***/
#define PTFPE (*(volatile uint8_t*)(0xFFFF8058))
#define PTFPE_PTFPE0                    0x01U
#define PTFPE_PTFPE1                    0x02U
#define PTFPE_PTFPE2                    0x04U
#define PTFPE_PTFPE3                    0x08U
#define PTFPE_PTFPE4                    0x10U
#define PTFPE_PTFPE5                    0x20U
#define PTFPE_PTFPE6                    0x40U
#define PTFPE_PTFPE7                    0x80U


/*** PTFSE - Port F Slew Rate Enable Register; 0xFFFF8059 ***/
#define PTFSE (*(volatile uint8_t*)(0xFFFF8059))
#define PTFSE_PTFSE0                    0x01U
#define PTFSE_PTFSE1                    0x02U
#define PTFSE_PTFSE2                    0x04U
#define PTFSE_PTFSE3                    0x08U
#define PTFSE_PTFSE4                    0x10U
#define PTFSE_PTFSE5                    0x20U
#define PTFSE_PTFSE6                    0x40U
#define PTFSE_PTFSE7                    0x80U


/*** PTFDS - Port F Drive Strength Selection Register; 0xFFFF805A ***/
#define PTFDS (*(volatile uint8_t*)(0xFFFF805A))
#define PTFDS_PTFDS0                    0x01U
#define PTFDS_PTFDS1                    0x02U
#define PTFDS_PTFDS2                    0x04U
#define PTFDS_PTFDS3                    0x08U
#define PTFDS_PTFDS4                    0x10U
#define PTFDS_PTFDS5                    0x20U
#define PTFDS_PTFDS6                    0x40U
#define PTFDS_PTFDS7                    0x80U


/*** PTFIFE - Port F Input Filter Enable Register; 0xFFFF805B ***/
#define PTFIFE (*(volatile uint8_t*)(0xFFFF805B))
#define PTFIFE_PTFIFE0                  0x01U
#define PTFIFE_PTFIFE1                  0x02U
#define PTFIFE_PTFIFE2                  0x04U
#define PTFIFE_PTFIFE3                  0x08U
#define PTFIFE_PTFIFE4                  0x10U
#define PTFIFE_PTFIFE5                  0x20U
#define PTFIFE_PTFIFE6                  0x40U
#define PTFIFE_PTFIFE7                  0x80U


/*** PTGD - Port G Data Register; 0xFFFF8060 ***/
#define PTGD (*(volatile uint8_t*)(0xFFFF8060))
#define PTGD_PTGD0                      0x01U
#define PTGD_PTGD1                      0x02U
#define PTGD_PTGD2                      0x04U
#define PTGD_PTGD3                      0x08U
#define PTGD_PTGD4                      0x10U
#define PTGD_PTGD5                      0x20U
#define PTGD_PTGD6                      0x40U
#define PTGD_PTGD7                      0x80U


/*** PTGDD - Port G Data Direction Register; 0xFFFF8061 ***/
#define PTGDD (*(volatile uint8_t*)(0xFFFF8061))
#define PTGDD_PTGDD0                    0x01U
#define PTGDD_PTGDD1                    0x02U
#define PTGDD_PTGDD2                    0x04U
#define PTGDD_PTGDD3                    0x08U
#define PTGDD_PTGDD4                    0x10U
#define PTGDD_PTGDD5                    0x20U
#define PTGDD_PTGDD6                    0x40U
#define PTGDD_PTGDD7                    0x80U


/*** PTGPE - Port G Pull Enable Register; 0xFFFF8068 ***/
#define PTGPE (*(volatile uint8_t*)(0xFFFF8068))
#define PTGPE_PTGPE0                    0x01U
#define PTGPE_PTGPE1                    0x02U
#define PTGPE_PTGPE2                    0x04U
#define PTGPE_PTGPE3                    0x08U
#define PTGPE_PTGPE4                    0x10U
#define PTGPE_PTGPE5                    0x20U
#define PTGPE_PTGPE6                    0x40U
#define PTGPE_PTGPE7                    0x80U


/*** PTGSE - Port G Slew Rate Enable Register; 0xFFFF8069 ***/
#define PTGSE (*(volatile uint8_t*)(0xFFFF8069))
#define PTGSE_PTGSE0                    0x01U
#define PTGSE_PTGSE1                    0x02U
#define PTGSE_PTGSE2                    0x04U
#define PTGSE_PTGSE3                    0x08U
#define PTGSE_PTGSE4                    0x10U
#define PTGSE_PTGSE5                    0x20U
#define PTGSE_PTGSE6                    0x40U
#define PTGSE_PTGSE7                    0x80U


/*** PTGDS - Port G Drive Strength Selection Register; 0xFFFF806A ***/
#define PTGDS (*(volatile uint8_t*)(0xFFFF806A))
#define PTGDS_PTGDS0                    0x01U
#define PTGDS_PTGDS1                    0x02U
#define PTGDS_PTGDS2                    0x04U
#define PTGDS_PTGDS3                    0x08U
#define PTGDS_PTGDS4                    0x10U
#define PTGDS_PTGDS5                    0x20U
#define PTGDS_PTGDS6                    0x40U
#define PTGDS_PTGDS7                    0x80U


/*** PTGIFE - Port G Input Filter Enable Register; 0xFFFF806B ***/
#define PTGIFE (*(volatile uint8_t*)(0xFFFF806B))
#define PTGIFE_PTGIFE0                  0x01U
#define PTGIFE_PTGIFE1                  0x02U
#define PTGIFE_PTGIFE2                  0x04U
#define PTGIFE_PTGIFE3                  0x08U
#define PTGIFE_PTGIFE4                  0x10U
#define PTGIFE_PTGIFE5                  0x20U
#define PTGIFE_PTGIFE6                  0x40U
#define PTGIFE_PTGIFE7                  0x80U


/*** PTHD - Port H Data Register; 0xFFFF8070 ***/
#define PTHD (*(volatile uint8_t*)(0xFFFF8070))
#define PTHD_PTHD0                      0x01U
#define PTHD_PTHD1                      0x02U
#define PTHD_PTHD2                      0x04U
#define PTHD_PTHD3                      0x08U
#define PTHD_PTHD4                      0x10U
#define PTHD_PTHD5                      0x20U
#define PTHD_PTHD6                      0x40U
#define PTHD_PTHD7                      0x80U


/*** PTHDD - Port H Data Direction Register; 0xFFFF8071 ***/
#define PTHDD (*(volatile uint8_t*)(0xFFFF8071))
#define PTHDD_PTHDD0                    0x01U
#define PTHDD_PTHDD1                    0x02U
#define PTHDD_PTHDD2                    0x04U
#define PTHDD_PTHDD3                    0x08U
#define PTHDD_PTHDD4                    0x10U
#define PTHDD_PTHDD5                    0x20U
#define PTHDD_PTHDD6                    0x40U
#define PTHDD_PTHDD7                    0x80U


/*** PTHPE - Port H Pull Enable Register; 0xFFFF8078 ***/
#define PTHPE (*(volatile uint8_t*)(0xFFFF8078))
#define PTHPE_PTHPE0                    0x01U
#define PTHPE_PTHPE1                    0x02U
#define PTHPE_PTHPE2                    0x04U
#define PTHPE_PTHPE3                    0x08U
#define PTHPE_PTHPE4                    0x10U
#define PTHPE_PTHPE5                    0x20U
#define PTHPE_PTHPE6                    0x40U
#define PTHPE_PTHPE7                    0x80U


/*** PTHSE - Port H Slew Rate Enable Register; 0xFFFF8079 ***/
#define PTHSE (*(volatile uint8_t*)(0xFFFF8079))
#define PTHSE_PTHSE0                    0x01U
#define PTHSE_PTHSE1                    0x02U
#define PTHSE_PTHSE2                    0x04U
#define PTHSE_PTHSE3                    0x08U
#define PTHSE_PTHSE4                    0x10U
#define PTHSE_PTHSE5                    0x20U
#define PTHSE_PTHSE6                    0x40U
#define PTHSE_PTHSE7                    0x80U


/*** PTHDS - Port H Drive Strength Selection Register; 0xFFFF807A ***/
#define PTHDS (*(volatile uint8_t*)(0xFFFF807A))
#define PTHDS_PTHDS0                    0x01U
#define PTHDS_PTHDS1                    0x02U
#define PTHDS_PTHDS2                    0x04U
#define PTHDS_PTHDS3                    0x08U
#define PTHDS_PTHDS4                    0x10U
#define PTHDS_PTHDS5                    0x20U
#define PTHDS_PTHDS6                    0x40U
#define PTHDS_PTHDS7                    0x80U


/*** PTHIFE - Port H Input Filter Enable Register; 0xFFFF807B ***/
#define PTHIFE (*(volatile uint8_t*)(0xFFFF807B))
#define PTHIFE_PTHIFE0                  0x01U
#define PTHIFE_PTHIFE1                  0x02U
#define PTHIFE_PTHIFE2                  0x04U
#define PTHIFE_PTHIFE3                  0x08U
#define PTHIFE_PTHIFE4                  0x10U
#define PTHIFE_PTHIFE5                  0x20U
#define PTHIFE_PTHIFE6                  0x40U
#define PTHIFE_PTHIFE7                  0x80U


/*** PTJD - Port J Data Register; 0xFFFF8080 ***/
#define PTJD (*(volatile uint8_t*)(0xFFFF8080))
#define PTJD_PTJD0                      0x01U
#define PTJD_PTJD1                      0x02U
#define PTJD_PTJD2                      0x04U
#define PTJD_PTJD3                      0x08U
#define PTJD_PTJD4                      0x10U
#define PTJD_PTJD5                      0x20U
#define PTJD_PTJD                       0x3FU
#define PTJD_PTJD_BITNUM                0x00U


/*** PTJDD - Port J Data Direction Register; 0xFFFF8081 ***/
#define PTJDD (*(volatile uint8_t*)(0xFFFF8081))
#define PTJDD_PTJDD0                    0x01U
#define PTJDD_PTJDD1                    0x02U
#define PTJDD_PTJDD2                    0x04U
#define PTJDD_PTJDD3                    0x08U
#define PTJDD_PTJDD4                    0x10U
#define PTJDD_PTJDD5                    0x20U
#define PTJDD_PTJDD                     0x3FU
#define PTJDD_PTJDD_BITNUM              0x00U


/*** PTJPE - Port J Pull Enable Register; 0xFFFF8088 ***/
#define PPTJPE (*(volatile uint8_t*)(0xFFFF8088))
#define PTJPE_PTJPE0                    0x01U
#define PTJPE_PTJPE1                    0x02U
#define PTJPE_PTJPE2                    0x04U
#define PTJPE_PTJPE3                    0x08U
#define PTJPE_PTJPE4                    0x10U
#define PTJPE_PTJPE5                    0x20U
#define PTJPE_PTJPE                     0x3FU
#define PTJPE_PTJPE_BITNUM              0x00U


/*** PTJSE - Port J Slew Rate Enable Register; 0xFFFF8089 ***/
#define PTJSE (*(volatile uint8_t*)(0xFFFF8089))
#define PTJSE_PTJSE0                    0x01U
#define PTJSE_PTJSE1                    0x02U
#define PTJSE_PTJSE2                    0x04U
#define PTJSE_PTJSE3                    0x08U
#define PTJSE_PTJSE4                    0x10U
#define PTJSE_PTJSE5                    0x20U
#define PTJSE_PTJSE                     0x3FU
#define PTJSE_PTJSE_BITNUM              0x00U


/*** PTJDS - Port J Drive Strength Selection Register; 0xFFFF808A ***/
#define PTJDS (*(volatile uint8_t*)(0xFFFF808A))
#define PTJDS_PTJDS0                    0x01U
#define PTJDS_PTJDS1                    0x02U
#define PTJDS_PTJDS2                    0x04U
#define PTJDS_PTJDS3                    0x08U
#define PTJDS_PTJDS4                    0x10U
#define PTJDS_PTJDS5                    0x20U
#define PTJDS_PTJDS                     0x3FU
#define PTJDS_PTJDS_BITNUM              0x00U


/*** PTJIFE - Port J Input Filter Enable Register; 0xFFFF808B ***/
#define PTJIFE (*(volatile uint8_t*)(0xFFFF808B))
#define PTJIFE_PTJIFE0                  0x01U
#define PTJIFE_PTJIFE1                  0x02U
#define PTJIFE_PTJIFE2                  0x04U
#define PTJIFE_PTJIFE3                  0x08U
#define PTJIFE_PTJIFE4                  0x10U
#define PTJIFE_PTJIFE5                  0x20U
#define PTJIFE_PTJIFE                   0x3FU
#define PTJIFE_PTJIFE_BITNUM            0x00U


/*** PTAPF1 - Port A Routing Register 1; 0xFFFF80C0 ***/
#define PTAPF1 (*(volatile uint8_t*)(0xFFFF80C0))
#define PTAPF1_A40                      0x01U
#define PTAPF1_A41                      0x02U
#define PTAPF1_A50                      0x04U
#define PTAPF1_A51                      0x08U
#define PTAPF1_A60                      0x10U
#define PTAPF1_A61                      0x20U
#define PTAPF1_A70                      0x40U
#define PTAPF1_A71                      0x80U
#define PTAPF1_A4                       0x03U
#define PTAPF1_A4_BITNUM                0x00U
#define PTAPF1_A5                       0x0CU
#define PTAPF1_A5_BITNUM                0x02U
#define PTAPF1_A6                       0x30U
#define PTAPF1_A6_BITNUM                0x04U
#define PTAPF1_A7                       0xC0U
#define PTAPF1_A7_BITNUM                0x06U


/*** PTAPF2 - Port A Routing Register 2; 0xFFFF80C1 ***/
#define PTAPF2 (*(volatile uint8_t*)(0xFFFF80C1))
#define PTAPF2_A00                      0x01U
#define PTAPF2_A01                      0x02U
#define PTAPF2_A10                      0x04U
#define PTAPF2_A11                      0x08U
#define PTAPF2_A20                      0x10U
#define PTAPF2_A21                      0x20U
#define PTAPF2_A30                      0x40U
#define PTAPF2_A31                      0x80U
#define PTAPF2_A0                       0x03U
#define PTAPF2_A0_BITNUM                0x00U
#define PTAPF2_A1                       0x0CU
#define PTAPF2_A1_BITNUM                0x02U
#define PTAPF2_A2                       0x30U
#define PTAPF2_A2_BITNUM                0x04U
#define PTAPF2_A3                       0xC0U
#define PTAPF2_A3_BITNUM                0x06U


/*** PTBPF1 - Port B Routing Register 1; 0xFFFF80C2 ***/
#define PTBPF1 (*(volatile uint8_t*)(0xFFFF80C2))
#define PTBPF1_B40                      0x01U
#define PTBPF1_B41                      0x02U
#define PTBPF1_B50                      0x04U
#define PTBPF1_B51                      0x08U
#define PTBPF1_B60                      0x10U
#define PTBPF1_B61                      0x20U
#define PTBPF1_B70                      0x40U
#define PTBPF1_B71                      0x80U
#define PTBPF1_B4                       0x03U
#define PTBPF1_B4_BITNUM                0x00U
#define PTBPF1_B5                       0x0CU
#define PTBPF1_B5_BITNUM                0x02U
#define PTBPF1_B6                       0x30U
#define PTBPF1_B6_BITNUM                0x04U
#define PTBPF1_B7                       0xC0U
#define PTBPF1_B7_BITNUM                0x06U


/*** PTBPF2 - Port B Routing Register 2; 0xFFFF80C3 ***/
#define PTBPF2 (*(volatile uint8_t*)(0xFFFF80C3))
#define PTBPF2_B00                      0x01U
#define PTBPF2_B01                      0x02U
#define PTBPF2_B10                      0x04U
#define PTBPF2_B11                      0x08U
#define PTBPF2_B20                      0x10U
#define PTBPF2_B21                      0x20U
#define PTBPF2_B30                      0x40U
#define PTBPF2_B31                      0x80U
#define PTBPF2_B0                       0x03U
#define PTBPF2_B0_BITNUM                0x00U
#define PTBPF2_B1                       0x0CU
#define PTBPF2_B1_BITNUM                0x02U
#define PTBPF2_B2                       0x30U
#define PTBPF2_B2_BITNUM                0x04U
#define PTBPF2_B3                       0xC0U
#define PTBPF2_B3_BITNUM                0x06U


/*** PTCPF1 - Port C Routing Register 1; 0xFFFF80C4 ***/
#define PTCPF1 (*(volatile uint8_t*)(0xFFFF80C4))
#define PTCPF1_C40                      0x01U
#define PTCPF1_C41                      0x02U
#define PTCPF1_C50                      0x04U
#define PTCPF1_C51                      0x08U
#define PTCPF1_C60                      0x10U
#define PTCPF1_C61                      0x20U
#define PTCPF1_C70                      0x40U
#define PTCPF1_C71                      0x80U
#define PTCPF1_C4                       0x03U
#define PTCPF1_C4_BITNUM                0x00U
#define PTCPF1_C5                       0x0CU
#define PTCPF1_C5_BITNUM                0x02U
#define PTCPF1_C6                       0x30U
#define PTCPF1_C6_BITNUM                0x04U
#define PTCPF1_C7                       0xC0U
#define PTCPF1_C7_BITNUM                0x06U


/*** PTCPF2 - Port C Routing Register 2; 0xFFFF80C5 ***/
#define PTCPF2 (*(volatile uint8_t*)(0xFFFF80C5))
#define PTCPF2_C00                      0x01U
#define PTCPF2_C01                      0x02U
#define PTCPF2_C10                      0x04U
#define PTCPF2_C11                      0x08U
#define PTCPF2_C20                      0x10U
#define PTCPF2_C21                      0x20U
#define PTCPF2_C30                      0x40U
#define PTCPF2_C31                      0x80U
#define PTCPF2_C0                       0x03U
#define PTCPF2_C0_BITNUM                0x00U
#define PTCPF2_C1                       0x0CU
#define PTCPF2_C1_BITNUM                0x02U
#define PTCPF2_C2                       0x30U
#define PTCPF2_C2_BITNUM                0x04U
#define PTCPF2_C3                       0xC0U
#define PTCPF2_C3_BITNUM                0x06U


/*** PTDPF1 - Port D Routing Register 1; 0xFFFF80C6 ***/
#define PTDPF1 (*(volatile uint8_t*)(0xFFFF80C6))
#define PTDPF1_D40                      0x01U
#define PTDPF1_D41                      0x02U
#define PTDPF1_D50                      0x04U
#define PTDPF1_D51                      0x08U
#define PTDPF1_D60                      0x10U
#define PTDPF1_D61                      0x20U
#define PTDPF1_D70                      0x40U
#define PTDPF1_D71                      0x80U
#define PTDPF1_D4                       0x03U
#define PTDPF1_D4_BITNUM                0x00U
#define PTDPF1_D5                       0x0CU
#define PTDPF1_D5_BITNUM                0x02U
#define PTDPF1_D6                       0x30U
#define PTDPF1_D6_BITNUM                0x04U
#define PTDPF1_D7                       0xC0U
#define PTDPF1_D7_BITNUM                0x06U


/*** PTDPF2 - Port D Routing Register 2; 0xFFFF80C7 ***/
#define PTDPF2 (*(volatile uint8_t*)(0xFFFF80C7))
#define PTDPF2_D00                      0x01U
#define PTDPF2_D01                      0x02U
#define PTDPF2_D10                      0x04U
#define PTDPF2_D11                      0x08U
#define PTDPF2_D20                      0x10U
#define PTDPF2_D21                      0x20U
#define PTDPF2_D30                      0x40U
#define PTDPF2_D31                      0x80U
#define PTDPF2_D0                       0x03U
#define PTDPF2_D0_BITNUM                0x00U
#define PTDPF2_D1                       0x0CU
#define PTDPF2_D1_BITNUM                0x02U
#define PTDPF2_D2                       0x30U
#define PTDPF2_D2_BITNUM                0x04U
#define PTDPF2_D3                       0xC0U
#define PTDPF2_D3_BITNUM                0x06U


/*** PTEPF1 - Port E Routing Register 1; 0xFFFF80C8 ***/
#define PTEPF1 (*(volatile uint8_t*)(0xFFFF80C8))
#define PTEPF1_E40                      0x01U
#define PTEPF1_E41                      0x02U
#define PTEPF1_E50                      0x04U
#define PTEPF1_E51                      0x08U
#define PTEPF1_E60                      0x10U
#define PTEPF1_E61                      0x20U
#define PTEPF1_E70                      0x40U
#define PTEPF1_E71                      0x80U
#define PTEPF1_E4                       0x03U
#define PTEPF1_E4_BITNUM                0x00U
#define PTEPF1_E5                       0x0CU
#define PTEPF1_E5_BITNUM                0x02U
#define PTEPF1_E6                       0x30U
#define PTEPF1_E6_BITNUM                0x04U
#define PTEPF1_E7                       0xC0U
#define PTEPF1_E7_BITNUM                0x06U


/*** PTEPF2 - Port E Routing Register 2; 0xFFFF80C9 ***/
#define PTEPF2 (*(volatile uint8_t*)(0xFFFF80C9))
#define PTEPF2_E00                      0x01U
#define PTEPF2_E01                      0x02U
#define PTEPF2_E10                      0x04U
#define PTEPF2_E11                      0x08U
#define PTEPF2_E20                      0x10U
#define PTEPF2_E21                      0x20U
#define PTEPF2_E30                      0x40U
#define PTEPF2_E31                      0x80U
#define PTEPF2_E0                       0x03U
#define PTEPF2_E0_BITNUM                0x00U
#define PTEPF2_E1                       0x0CU
#define PTEPF2_E1_BITNUM                0x02U
#define PTEPF2_E2                       0x30U
#define PTEPF2_E2_BITNUM                0x04U
#define PTEPF2_E3                       0xC0U
#define PTEPF2_E3_BITNUM                0x06U


/*** PTFPF1 - Port F Routing Register 1; 0xFFFF80CA ***/
#define PTFPF1 (*(volatile uint8_t*)(0xFFFF80CA))
#define PTFPF1_F40                      0x01U
#define PTFPF1_F41                      0x02U
#define PTFPF1_F50                      0x04U
#define PTFPF1_F51                      0x08U
#define PTFPF1_F60                      0x10U
#define PTFPF1_F61                      0x20U
#define PTFPF1_F70                      0x40U
#define PTFPF1_F71                      0x80U
#define PTFPF1_F4                       0x03U
#define PTFPF1_F4_BITNUM                0x00U
#define PTFPF1_F5                       0x0CU
#define PTFPF1_F5_BITNUM                0x02U
#define PTFPF1_F6                       0x30U
#define PTFPF1_F6_BITNUM                0x04U
#define PTFPF1_F7                       0xC0U
#define PTFPF1_F7_BITNUM                0x06U


/*** PTFPF2 - Port F Routing Register 2; 0xFFFF80CB ***/
#define PTFPF2 (*(volatile uint8_t*)(0xFFFF80CB))
#define PTFPF2_F00                      0x01U
#define PTFPF2_F01                      0x02U
#define PTFPF2_F10                      0x04U
#define PTFPF2_F11                      0x08U
#define PTFPF2_F20                      0x10U
#define PTFPF2_F21                      0x20U
#define PTFPF2_F30                      0x40U
#define PTFPF2_F31                      0x80U
#define PTFPF2_F0                       0x03U
#define PTFPF2_F0_BITNUM                0x00U
#define PTFPF2_F1                       0x0CU
#define PTFPF2_F1_BITNUM                0x02U
#define PTFPF2_F2                       0x30U
#define PTFPF2_F2_BITNUM                0x04U
#define PTFPF2_F3                       0xC0U
#define PTFPF2_F3_BITNUM                0x06U


/*** PTGPF1 - Port G Routing Register 1; 0xFFFF80CC ***/
#define PTGPF1 (*(volatile uint8_t*)(0xFFFF80CC))
#define PTGPF1_G40                      0x01U
#define PTGPF1_G41                      0x02U
#define PTGPF1_G50                      0x04U
#define PTGPF1_G51                      0x08U
#define PTGPF1_G60                      0x10U
#define PTGPF1_G61                      0x20U
#define PTGPF1_G70                      0x40U
#define PTGPF1_G71                      0x80U
#define PTGPF1_G4                       0x03U
#define PTGPF1_G4_BITNUM                0x00U
#define PTGPF1_G5                       0x0CU
#define PTGPF1_G5_BITNUM                0x02U
#define PTGPF1_G6                       0x30U
#define PTGPF1_G6_BITNUM                0x04U
#define PTGPF1_G7                       0xC0U
#define PTGPF1_G7_BITNUM                0x06U


/*** PTGPF2 - Port G Routing Register 2; 0xFFFF80CD ***/
#define PTGPF2 (*(volatile uint8_t*)(0xFFFF80CD))
#define PTGPF2_G00                      0x01U
#define PTGPF2_G01                      0x02U
#define PTGPF2_G10                      0x04U
#define PTGPF2_G11                      0x08U
#define PTGPF2_G20                      0x10U
#define PTGPF2_G21                      0x20U
#define PTGPF2_G30                      0x40U
#define PTGPF2_G31                      0x80U
#define PTGPF2_G0                       0x03U
#define PTGPF2_G0_BITNUM                0x00U
#define PTGPF2_G1                       0x0CU
#define PTGPF2_G1_BITNUM                0x02U
#define PTGPF2_G2                       0x30U
#define PTGPF2_G2_BITNUM                0x04U
#define PTGPF2_G3                       0xC0U
#define PTGPF2_G3_BITNUM                0x06U


/*** PTHPF1 - Port H Routing Register 1; 0xFFFF80CE ***/
#define PTHPF1 (*(volatile uint8_t*)(0xFFFF80CE))
#define PTHPF1_H40                      0x01U
#define PTHPF1_H41                      0x02U
#define PTHPF1_H50                      0x04U
#define PTHPF1_H51                      0x08U
#define PTHPF1_H60                      0x10U
#define PTHPF1_H61                      0x20U
#define PTHPF1_H70                      0x40U
#define PTHPF1_H71                      0x80U
#define PTHPF1_H4                       0x03U
#define PTHPF1_H4_BITNUM                0x00U
#define PTHPF1_H5                       0x0CU
#define PTHPF1_H5_BITNUM                0x02U
#define PTHPF1_H6                       0x30U
#define PTHPF1_H6_BITNUM                0x04U
#define PTHPF1_H7                       0xC0U
#define PTHPF1_H7_BITNUM                0x06U


/*** PTHPF2 - Port H Routing Register 2; 0xFFFF80CF ***/
#define PTHPF2 (*(volatile uint8_t*)(0xFFFF80CF))
#define PTHPF2_H00                      0x01U
#define PTHPF2_H01                      0x02U
#define PTHPF2_H10                      0x04U
#define PTHPF2_H11                      0x08U
#define PTHPF2_H20                      0x10U
#define PTHPF2_H21                      0x20U
#define PTHPF2_H30                      0x40U
#define PTHPF2_H31                      0x80U
#define PTHPF2_H0                       0x03U
#define PTHPF2_H0_BITNUM                0x00U
#define PTHPF2_H1                       0x0CU
#define PTHPF2_H1_BITNUM                0x02U
#define PTHPF2_H2                       0x30U
#define PTHPF2_H2_BITNUM                0x04U
#define PTHPF2_H3                       0xC0U
#define PTHPF2_H3_BITNUM                0x06U


/*** PTJPF1 - Port J Routing Register 1; 0xFFFF80D0 ***/
#define PTJPF1 (*(volatile uint8_t*)(0xFFFF80D0))
#define PTJPF1_J40                      0x01U
#define PTJPF1_J41                      0x02U
#define PTJPF1_J50                      0x04U
#define PTJPF1_J51                      0x08U
#define PTJPF1_J4                       0x03U
#define PTJPF1_J4_BITNUM                0x00U
#define PTJPF1_J5                       0x0CU
#define PTJPF1_J5_BITNUM                0x02U


/*** PTJPF2 - Port J Routing Register 2; 0xFFFF80D1 ***/
#define PTJPF2 (*(volatile uint8_t*)(0xFFFF80D1))
#define PTJPF2_J00                      0x01U
#define PTJPF2_J01                      0x02U
#define PTJPF2_J10                      0x04U
#define PTJPF2_J11                      0x08U
#define PTJPF2_J20                      0x10U
#define PTJPF2_J21                      0x20U
#define PTJPF2_J30                      0x40U
#define PTJPF2_J31                      0x80U
#define PTJPF2_J0                       0x03U
#define PTJPF2_J0_BITNUM                0x00U
#define PTJPF2_J1                       0x0CU
#define PTJPF2_J1_BITNUM                0x02U
#define PTJPF2_J2                       0x30U
#define PTJPF2_J2_BITNUM                0x04U
#define PTJPF2_J3                       0xC0U
#define PTJPF2_J3_BITNUM                0x06U


/*** IRQSC - Interrupt request status and control register; 0xFFFF80E0 ***/
#define IRQSC (*(volatile uint8_t*)(0xFFFF80E0))
#define IRQSC_IRQMOD                    0x01U
#define IRQSC_IRQIE                     0x02U
#define IRQSC_IRQACK                    0x04U
#define IRQSC_IRQF                      0x08U
#define IRQSC_IRQPE                     0x10U
#define IRQSC_IRQEDG                    0x20U
#define IRQSC_IRQPDD                    0x40U


/*** SRS - System Reset Status Register; 0xFFFF8100 ***/
#define SRS (*(volatile uint8_t*)(0xFFFF8100))
#define SRS_LVD                         0x02U
#define SRS_LOC                         0x04U
#define SRS_ILAD                        0x08U
#define SRS_ILOP                        0x10U
#define SRS_COP                         0x20U
#define SRS_PIN                         0x40U
#define SRS_POR                         0x80U












/*** TPM1SC - TPM1 Status and Control Register; 0xFFFF8260 ***/
#define TPM1SC (*(volatile uint8_t*)(0xFFFF8260))
#define TPM1SC_PS0                      0x01U
#define TPM1SC_PS1                      0x02U
#define TPM1SC_PS2                      0x04U
#define TPM1SC_CLKSA                    0x08U
#define TPM1SC_CLKSB                    0x10U
#define TPM1SC_CPWMS                    0x20U
#define TPM1SC_TOIE                     0x40U
#define TPM1SC_TOF                      0x80U
#define TPM1SC_PS                       0x07U
#define TPM1SC_PS_BITNUM                0x00U
#define TPM1SC_CLKSx                    0x18U
#define TPM1SC_CLKSx_BITNUM             0x03U


/*** TPM1CNT - TPM1 Timer Counter Register; 0xFFFF8261 ***/
#define TPM1CNT (*(volatile uint16_t*)(0xFFFF8261))


/*** TPM1MOD - TPM1 Timer Counter Modulo Register; 0xFFFF8263 ***/
#define TPM1MOD (*(volatile uint16_t*)(0xFFFF8263))


/*** TPM1C0SC - TPM1 Timer Channel 0 Status and Control Register; 0xFFFF8265 ***/
#define TPM1C0SC (*(volatile uint8_t*)(0xFFFF8265))
#define TPM1C0SC_ELS0A                  0x04U
#define TPM1C0SC_ELS0B                  0x08U
#define TPM1C0SC_MS0A                   0x10U
#define TPM1C0SC_MS0B                   0x20U
#define TPM1C0SC_CH0IE                  0x40U
#define TPM1C0SC_CH0F                   0x80U
#define TPM1C0SC_ELS0x                  0x0CU
#define TPM1C0SC_ELS0x_BITNUM           0x02U
#define TPM1C0SC_MS0x                   0x30U
#define TPM1C0SC_MS0x_BITNUM            0x04U


/*** TPM1C0V - TPM1 Timer Channel 0 Value Register; 0xFFFF8266 ***/
#define TPM1C0V (*(volatile uint16_t*)(0xFFFF8266))


/*** TPM1C1SC - TPM1 Timer Channel 1 Status and Control Register; 0xFFFF8268 ***/
#define TPM1C1SC (*(volatile uint8_t*)(0xFFFF8268))
#define TPM1C1SC_ELS1A                  0x04U
#define TPM1C1SC_ELS1B                  0x08U
#define TPM1C1SC_MS1A                   0x10U
#define TPM1C1SC_MS1B                   0x20U
#define TPM1C1SC_CH1IE                  0x40U
#define TPM1C1SC_CH1F                   0x80U
#define TPM1C1SC_ELS1x                  0x0CU
#define TPM1C1SC_ELS1x_BITNUM           0x02U
#define TPM1C1SC_MS1x                   0x30U
#define TPM1C1SC_MS1x_BITNUM            0x04U


/*** TPM1C1V - TPM1 Timer Channel 1 Value Register; 0xFFFF8269 ***/
#define TPM1C1V (*(volatile uint16_t*)(0xFFFF8269))


/*** TPM1C2SC - TPM1 Timer Channel 2 Status and Control Register; 0xFFFF826B ***/
#define TPM1C2SC (*(volatile uint8_t*)(0xFFFF826B))
#define TPM1C2SC_ELS2A                  0x04U
#define TPM1C2SC_ELS2B                  0x08U
#define TPM1C2SC_MS2A                   0x10U
#define TPM1C2SC_MS2B                   0x20U
#define TPM1C2SC_CH2IE                  0x40U
#define TPM1C2SC_CH2F                   0x80U
#define TPM1C2SC_ELS2x                  0x0CU
#define TPM1C2SC_ELS2x_BITNUM           0x02U
#define TPM1C2SC_MS2x                   0x30U
#define TPM1C2SC_MS2x_BITNUM            0x04U


/*** TPM1C2V - TPM1 Timer Channel 2 Value Register; 0xFFFF826C ***/
#define TPM1C2V (*(volatile uint16_t*)(0xFFFF826C))


/*** TPM2SC - TPM2 Status and Control Register; 0xFFFF8280 ***/
#define TPM2SC (*(volatile uint8_t*)(0xFFFF8280))

#define TPM2SC_PS0                      0x01U
#define TPM2SC_PS1                      0x02U
#define TPM2SC_PS2                      0x04U
#define TPM2SC_CLKSA                    0x08U
#define TPM2SC_CLKSB                    0x10U
#define TPM2SC_CPWMS                    0x20U
#define TPM2SC_TOIE                     0x40U
#define TPM2SC_TOF                      0x80U
#define TPM2SC_PS                       0x07U
#define TPM2SC_PS_BITNUM                0x00U
#define TPM2SC_CLKSx                    0x18U
#define TPM2SC_CLKSx_BITNUM             0x03U


/*** TPM2CNT - TPM2 Timer Counter Register; 0xFFFF8281 ***/
#define TPM2CNT (*(volatile uint16_t*)(0xFFFF8281))

/*** TPM2MOD - TPM2 Timer Counter Modulo Register; 0xFFFF8283 ***/
#define TPM2MOD (*(volatile uint16_t*)(0xFFFF8283))

/*** TPM2C0SC - TPM2 Timer Channel 0 Status and Control Register; 0xFFFF8285 ***/
#define TPM2C0SC (*(volatile uint8_t*)(0xFFFF8285))

#define TPM2C0SC_ELS0A                  0x04U
#define TPM2C0SC_ELS0B                  0x08U
#define TPM2C0SC_MS0A                   0x10U
#define TPM2C0SC_MS0B                   0x20U
#define TPM2C0SC_CH0IE                  0x40U
#define TPM2C0SC_CH0F                   0x80U
#define TPM2C0SC_ELS0x                  0x0CU
#define TPM2C0SC_ELS0x_BITNUM           0x02U
#define TPM2C0SC_MS0x                   0x30U
#define TPM2C0SC_MS0x_BITNUM            0x04U


/*** TPM2C0V - TPM2 Timer Channel 0 Value Register; 0xFFFF8286 ***/
#define TPM2C0V (*(volatile uint16_t*)(0xFFFF8286))


/*** TPM2C1SC - TPM2 Timer Channel 1 Status and Control Register; 0xFFFF8288 ***/
#define TPM2C1SC (*(volatile uint8_t*)(0xFFFF8288))
#define TPM2C1SC_ELS1A                  0x04U
#define TPM2C1SC_ELS1B                  0x08U
#define TPM2C1SC_MS1A                   0x10U
#define TPM2C1SC_MS1B                   0x20U
#define TPM2C1SC_CH1IE                  0x40U
#define TPM2C1SC_CH1F                   0x80U
#define TPM2C1SC_ELS1x                  0x0CU
#define TPM2C1SC_ELS1x_BITNUM           0x02U
#define TPM2C1SC_MS1x                   0x30U
#define TPM2C1SC_MS1x_BITNUM            0x04U


/*** TPM2C1V - TPM2 Timer Channel 1 Value Register; 0xFFFF8289 ***/
#define TPM2C1V (*(volatile uint16_t*)(0xFFFF8289))


/*** TPM2C2SC - TPM2 Timer Channel 2 Status and Control Register; 0xFFFF828B ***/
#define TPM2C2SC (*(volatile uint8_t*)(0xFFFF828B))
#define TPM2C2SC_ELS2A                  0x04U
#define TPM2C2SC_ELS2B                  0x08U
#define TPM2C2SC_MS2A                   0x10U
#define TPM2C2SC_MS2B                   0x20U
#define TPM2C2SC_CH2IE                  0x40U
#define TPM2C2SC_CH2F                   0x80U
#define TPM2C2SC_ELS2x                  0x0CU
#define TPM2C2SC_ELS2x_BITNUM           0x02U
#define TPM2C2SC_MS2x                   0x30U
#define TPM2C2SC_MS2x_BITNUM            0x04U


/*** TPM2C2V - TPM2 Timer Channel 2 Value Register; 0xFFFF828C ***/
#define TPM2C2V (*(volatile uint16_t*)(0xFFFF828C))


/*** MTIM1SC - MTIM Clock Configuration Register; 0xFFFF82A0 ***/
#define MTIM1SC (*(volatile uint8_t*)(0xFFFF82A0))
#define MTIM1SC_TSTP                    0x10U
#define MTIM1SC_TRST                    0x20U
#define MTIM1SC_TOIE                    0x40U
#define MTIM1SC_TOF                     0x80U


/*** MTIM1CLK - MTIM Clock Configuration Register; 0xFFFF82A1 ***/
#define MTIM1CLK (*(volatile uint8_t*)(0xFFFF82A1))
#define MTIM1CLK_PS0                    0x01U
#define MTIM1CLK_PS1                    0x02U
#define MTIM1CLK_PS2                    0x04U
#define MTIM1CLK_PS3                    0x08U
#define MTIM1CLK_CLKS0                  0x10U
#define MTIM1CLK_CLKS1                  0x20U
#define MTIM1CLK_PS                     0x0FU
#define MTIM1CLK_PS_BITNUM              0x00U
#define MTIM1CLK_CLKS                   0x30U
#define MTIM1CLK_CLKS_BITNUM            0x04U


/*** MTIM1CNT - MTIM Counter Register; 0xFFFF82A2 ***/
#define MTIM1CNT (*(volatile uint8_t*)(0xFFFF82A2))

/*** MTIM1MOD - MTIM Modulo Register; 0xFFFF82A3 ***/
#define MTIM1MOD (*(volatile uint8_t*)(0xFFFF82A3))


/*** FCDIV - FLASH Clock Divider Register; 0xFFFF82E0 ***/
#define FCDIV (*(volatile uint8_t*)(0xFFFF82E0))
#define FCDIV_FDIV0                     0x01U
#define FCDIV_FDIV1                     0x02U
#define FCDIV_FDIV2                     0x04U
#define FCDIV_FDIV3                     0x08U
#define FCDIV_FDIV4                     0x10U
#define FCDIV_FDIV5                     0x20U
#define FCDIV_PRDIV8                    0x40U
#define FCDIV_FDIVLD                    0x80U
#define FCDIV_FDIV                      0x3FU
#define FCDIV_FDIV_BITNUM               0x00U


/*** FOPT - Flash Options Register; 0xFFFF82E1 ***/
#define FOPT (*(volatile uint8_t*)(0xFFFF82E1))
#define FOPT_SEC0                       0x01U
#define FOPT_SEC1                       0x02U
#define FOPT_KEYEN0                     0x40U
#define FOPT_KEYEN1                     0x80U
#define FOPT_SEC                        0x03U
#define FOPT_SEC_BITNUM                 0x00U
#define FOPT_KEYEN                      0xC0U
#define FOPT_KEYEN_BITNUM               0x06U


/*** FCNFG - Flash Configuration Register; 0xFFFF82E3 ***/
#define FCNFG (*(volatile uint8_t*)(0xFFFF82E3))
#define FCNFG_KEYACC                    0x20U


/*** FPROT - Flash Protection Register; 0xFFFF82E4 ***/
#define FPROT (*(volatile uint8_t*)(0xFFFF82E4))
#define FPROT_FPOPEN                    0x01U
#define FPROT_FPS0                      0x02U
#define FPROT_FPS1                      0x04U
#define FPROT_FPS2                      0x08U
#define FPROT_FPS3                      0x10U
#define FPROT_FPS4                      0x20U
#define FPROT_FPS5                      0x40U
#define FPROT_FPS6                      0x80U
#define FPROT_FPS                       0xFEU
#define FPROT_FPS_BITNUM                0x01U


/*** FSTAT - Flash Status Register; 0xFFFF82E5 ***/
#define FSTAT (*(volatile uint8_t*)(0xFFFF82E5))
#define FSTAT_FBLANK                    0x04U
#define FSTAT_FACCERR                   0x10U
#define FSTAT_FPVIOL                    0x20U
#define FSTAT_FCCF                      0x40U
#define FSTAT_FCBEF                     0x80U


/*** FCMD - Flash Command Register; 0xFFFF82E6 ***/
#define FCMD (*(volatile uint8_t*)(0xFFFF82E6))
#define FCMD_FCMD0                      0x01U
#define FCMD_FCMD1                      0x02U
#define FCMD_FCMD2                      0x04U
#define FCMD_FCMD3                      0x08U
#define FCMD_FCMD4                      0x10U
#define FCMD_FCMD5                      0x20U
#define FCMD_FCMD6                      0x40U
#define FCMD_FCMD                       0x7FU
#define FCMD_FCMD_BITNUM                0x00U


/*** MTIM2SC - MTIM Clock Configuration Register; 0xFFFF8300 ***/
#define MTIM2SC (*(volatile uint8_t*)(0xFFFF8300))
#define MTIM2SC_TSTP                    0x10U
#define MTIM2SC_TRST                    0x20U
#define MTIM2SC_TOIE                    0x40U
#define MTIM2SC_TOF                     0x80U


/*** MTIM2CLK - MTIM Clock Configuration Register; 0xFFFF8301 ***/
#define MTIM2CLK (*(volatile uint8_t*)(0xFFFF8301))
#define MTIM2CLK_PS0                    0x01U
#define MTIM2CLK_PS1                    0x02U
#define MTIM2CLK_PS2                    0x04U
#define MTIM2CLK_PS3                    0x08U
#define MTIM2CLK_CLKS0                  0x10U
#define MTIM2CLK_CLKS1                  0x20U
#define MTIM2CLK_PS                     0x0FU
#define MTIM2CLK_PS_BITNUM              0x00U
#define MTIM2CLK_CLKS                   0x30U
#define MTIM2CLK_CLKS_BITNUM            0x04U


/*** MTIM2CNT - MTIM Counter Register; 0xFFFF8302 ***/
#define MTIM2CNT (*(volatile uint8_t*)(0xFFFF8302))

/*** MTIM2MOD - MTIM Modulo Register; 0xFFFF8303 ***/
#define MTIM2MOD (*(volatile uint8_t*)(0xFFFF8303))



/*** CSAR0 - Chip Select Address Register 0; 0xFFFFE800 ***/
#define CSAR0 (*(volatile uint32_t*)(0xFFFFE800))
#define CSAR0_BA0                       0x00010000UL
#define CSAR0_BA1                       0x00020000UL
#define CSAR0_BA2                       0x00040000UL
#define CSAR0_BA3                       0x00080000UL
#define CSAR0_BA4                       0x00100000UL
#define CSAR0_BA5                       0x00200000UL
#define CSAR0_BA6                       0x00400000UL
#define CSAR0_BA7                       0x00800000UL
#define CSAR0_BA8                       0x01000000UL
#define CSAR0_BA9                       0x02000000UL
#define CSAR0_BA10                      0x04000000UL
#define CSAR0_BA11                      0x08000000UL
#define CSAR0_BA12                      0x10000000UL
#define CSAR0_BA13                      0x20000000UL
#define CSAR0_BA14                      0x40000000UL
#define CSAR0_BA15                      0x80000000UL
#define CSAR0_BA                        0xFFFF0000U
#define CSAR0_BA_BITNUM                 0x10U


/*** CSMR0 - Chip Select Mask Register 0; 0xFFFFE804 ***/
#define CSMR0 (*(volatile uint32_t*)(0xFFFFE804))
#define CSMR0_V                         0x01UL
#define CSMR0_WP                        0x0100UL
#define CSMR0_BAM0                      0x00010000UL
#define CSMR0_BAM1                      0x00020000UL
#define CSMR0_BAM2                      0x00040000UL
#define CSMR0_BAM3                      0x00080000UL
#define CSMR0_BAM4                      0x00100000UL
#define CSMR0_BAM5                      0x00200000UL
#define CSMR0_BAM6                      0x00400000UL
#define CSMR0_BAM7                      0x00800000UL
#define CSMR0_BAM8                      0x01000000UL
#define CSMR0_BAM9                      0x02000000UL
#define CSMR0_BAM10                     0x04000000UL
#define CSMR0_BAM11                     0x08000000UL
#define CSMR0_BAM12                     0x10000000UL
#define CSMR0_BAM13                     0x20000000UL
#define CSMR0_BAM14                     0x40000000UL
#define CSMR0_BAM15                     0x80000000UL
#define CSMR0_BAM                       0xFFFF0000U
#define CSMR0_BAM_BITNUM                0x10U


/*** CSCR0 - Chip Select Control Register 0; 0xFFFFE808 ***/
#define CSCR0 (*(volatile uint32_t*)(0xFFFFE808))
#define CSCR0_PS0                       0x40UL
#define CSCR0_PS1                       0x80UL
#define CSCR0_AA                        0x0100UL
#define CSCR0_MUX                       0x0200UL
#define CSCR0_WS0                       0x0400UL
#define CSCR0_WS1                       0x0800UL
#define CSCR0_WS2                       0x1000UL
#define CSCR0_WS3                       0x2000UL
#define CSCR0_WS4                       0x4000UL
#define CSCR0_WS5                       0x8000UL
#define CSCR0_WRAH0                     0x00010000UL
#define CSCR0_WRAH1                     0x00020000UL
#define CSCR0_RDAH0                     0x00040000UL
#define CSCR0_RDAH1                     0x00080000UL
#define CSCR0_ASET0                     0x00100000UL
#define CSCR0_ASET1                     0x00200000UL
#define CSCR0_PS                        0xC0U
#define CSCR0_PS_BITNUM                 0x06U
#define CSCR0_WS                        0xFC00U
#define CSCR0_WS_BITNUM                 0x0AU
#define CSCR0_WRAH                      0x00030000U
#define CSCR0_WRAH_BITNUM               0x10U
#define CSCR0_RDAH                      0x000C0000U
#define CSCR0_RDAH_BITNUM               0x12U
#define CSCR0_ASET                      0x00300000U
#define CSCR0_ASET_BITNUM               0x14U


/*** CSAR1 - Chip Select Address Register 1; 0xFFFFE80C ***/
#define CSAR1 (*(volatile uint32_t*)(0xFFFFE80C))
#define CSAR1_BA0                       0x00010000UL
#define CSAR1_BA1                       0x00020000UL
#define CSAR1_BA2                       0x00040000UL
#define CSAR1_BA3                       0x00080000UL
#define CSAR1_BA4                       0x00100000UL
#define CSAR1_BA5                       0x00200000UL
#define CSAR1_BA6                       0x00400000UL
#define CSAR1_BA7                       0x00800000UL
#define CSAR1_BA8                       0x01000000UL
#define CSAR1_BA9                       0x02000000UL
#define CSAR1_BA10                      0x04000000UL
#define CSAR1_BA11                      0x08000000UL
#define CSAR1_BA12                      0x10000000UL
#define CSAR1_BA13                      0x20000000UL
#define CSAR1_BA14                      0x40000000UL
#define CSAR1_BA15                      0x80000000UL
#define CSAR1_BA                        0xFFFF0000U
#define CSAR1_BA_BITNUM                 0x10U


/*** CSMR1 - Chip Select Mask Register 1; 0xFFFFE810 ***/
#define CSMR1 (*(volatile uint32_t*)(0xFFFFE810))
#define CSMR1_V                         0x01UL
#define CSMR1_WP                        0x0100UL
#define CSMR1_BAM0                      0x00010000UL
#define CSMR1_BAM1                      0x00020000UL
#define CSMR1_BAM2                      0x00040000UL
#define CSMR1_BAM3                      0x00080000UL
#define CSMR1_BAM4                      0x00100000UL
#define CSMR1_BAM5                      0x00200000UL
#define CSMR1_BAM6                      0x00400000UL
#define CSMR1_BAM7                      0x00800000UL
#define CSMR1_BAM8                      0x01000000UL
#define CSMR1_BAM9                      0x02000000UL
#define CSMR1_BAM10                     0x04000000UL
#define CSMR1_BAM11                     0x08000000UL
#define CSMR1_BAM12                     0x10000000UL
#define CSMR1_BAM13                     0x20000000UL
#define CSMR1_BAM14                     0x40000000UL
#define CSMR1_BAM15                     0x80000000UL
#define CSMR1_BAM                       0xFFFF0000U
#define CSMR1_BAM_BITNUM                0x10U


/*** CSCR1 - Chip Select Control Register 1; 0xFFFFE814 ***/
#define CSCR1 (*(volatile uint32_t*)(0xFFFFE814))
#define CSCR1_PS0                       0x40UL
#define CSCR1_PS1                       0x80UL
#define CSCR1_AA                        0x0100UL
#define CSCR1_MUX                       0x0200UL
#define CSCR1_WS0                       0x0400UL
#define CSCR1_WS1                       0x0800UL
#define CSCR1_WS2                       0x1000UL
#define CSCR1_WS3                       0x2000UL
#define CSCR1_WS4                       0x4000UL
#define CSCR1_WS5                       0x8000UL
#define CSCR1_WRAH0                     0x00010000UL
#define CSCR1_WRAH1                     0x00020000UL
#define CSCR1_RDAH0                     0x00040000UL
#define CSCR1_RDAH1                     0x00080000UL
#define CSCR1_ASET0                     0x00100000UL
#define CSCR1_ASET1                     0x00200000UL
#define CSCR1_PS                        0xC0U
#define CSCR1_PS_BITNUM                 0x06U
#define CSCR1_WS                        0xFC00U
#define CSCR1_WS_BITNUM                 0x0AU
#define CSCR1_WRAH                      0x00030000U
#define CSCR1_WRAH_BITNUM               0x10U
#define CSCR1_RDAH                      0x000C0000U
#define CSCR1_RDAH_BITNUM               0x12U
#define CSCR1_ASET                      0x00300000U
#define CSCR1_ASET_BITNUM               0x14U


/*** INTC_ORMR - INTC OR Mask Register; 0xFFFFFFCC ***/
#define INTC_ORMR (*(volatile uint32_t*)(0xFFFFFFCC))
#define INTC_ORMR_SCI3DO                0x20U
#define INTC_ORMR_FECDO                 0x0100U


/*** INTC_FRC - INTC Force Interrupt Register; 0xFFFFFFD0 ***/
#define INTC_FRC (*(volatile uint8_t*)(0xFFFFFFD0))

#define INTC_FRC_LVL7                   0x01U
#define INTC_FRC_LVL6                   0x02U
#define INTC_FRC_LVL5                   0x04U
#define INTC_FRC_LVL4                   0x08U
#define INTC_FRC_LVL3                   0x10U
#define INTC_FRC_LVL2                   0x20U
#define INTC_FRC_LVL1                   0x40U


/*** INTC_PL6P7 - INTC Programmable Level 6, Priority 7 Register; 0xFFFFFFD8 ***/
#define INTC_PL6P7 (*(volatile uint8_t*)(0xFFFFFFD8))
#define INTC_PL6P7_REQN0                0x01U
#define INTC_PL6P7_REQN1                0x02U
#define INTC_PL6P7_REQN2                0x04U
#define INTC_PL6P7_REQN3                0x08U
#define INTC_PL6P7_REQN4                0x10U
#define INTC_PL6P7_REQN5                0x20U
#define INTC_PL6P7_REQN                 0x3FU
#define INTC_PL6P7_REQN_BITNUM          0x00U


/*** INTC_PL6P6 - INTC Programmable Level 6, Priority 6 Register; 0xFFFFFFD9 ***/
#define INTC_PL6P6 (*(volatile uint8_t*)(0xFFFFFFD9))
#define INTC_PL6P6_REQN0                0x01U
#define INTC_PL6P6_REQN1                0x02U
#define INTC_PL6P6_REQN2                0x04U
#define INTC_PL6P6_REQN3                0x08U
#define INTC_PL6P6_REQN4                0x10U
#define INTC_PL6P6_REQN5                0x20U
#define INTC_PL6P6_REQN                 0x3FU
#define INTC_PL6P6_REQN_BITNUM          0x00U


/*** INTC_WCR - INTC Wake-up Control Register; 0xFFFFFFDB ***/
#define INTC_WCR (*(volatile uint8_t*)(0xFFFFFFDB))
#define INTC_WCR_MASK0                  0x01U
#define INTC_WCR_MASK1                  0x02U
#define INTC_WCR_MASK2                  0x04U
#define INTC_WCR_ENB                    0x80U
#define INTC_WCR_MASK                   0x07U
#define INTC_WCR_MASK_BITNUM            0x00U


/*** INTC_SFRC - INTC Set Interrupt Force Register; 0xFFFFFFDE ***/
#define INTC_SFRC (*(volatile uint8_t*)(0xFFFFFFDE))
#define INTC_SFRC_SET0                  0x01U
#define INTC_SFRC_SET1                  0x02U
#define INTC_SFRC_SET2                  0x04U
#define INTC_SFRC_SET3                  0x08U
#define INTC_SFRC_SET4                  0x10U
#define INTC_SFRC_SET5                  0x20U
#define INTC_SFRC_SET                   0x3FU
#define INTC_SFRC_SET_BITNUM            0x00U


/*** INTC_CFRC - INTC Clear Interrupt Force Register; 0xFFFFFFDF ***/
#define INTC_CFRC (*(volatile uint8_t*)(0xFFFFFFDF))
#define INTC_CFRC_CLR0                  0x01U
#define INTC_CFRC_CLR1                  0x02U
#define INTC_CFRC_CLR2                  0x04U
#define INTC_CFRC_CLR3                  0x08U
#define INTC_CFRC_CLR4                  0x10U
#define INTC_CFRC_CLR5                  0x20U
#define INTC_CFRC_CLR                   0x3FU
#define INTC_CFRC_CLR_BITNUM            0x00U


/*** INTC_SWIACK - INTC Software IACK Register; 0xFFFFFFE0 ***/
#define INTC_SWIACK (*(volatile uint8_t*)(0xFFFFFFE0))
#define INTC_SWIACK_VECN0               0x01U
#define INTC_SWIACK_VECN1               0x02U
#define INTC_SWIACK_VECN2               0x04U
#define INTC_SWIACK_VECN3               0x08U
#define INTC_SWIACK_VECN4               0x10U
#define INTC_SWIACK_VECN5               0x20U
#define INTC_SWIACK_VECN6               0x40U
#define INTC_SWIACK_VECN                0x7FU
#define INTC_SWIACK_VECN_BITNUM         0x00U


/*** INTC_LVL1IACK - INTC Level 1 IACK Register; 0xFFFFFFE4 ***/
#define INTC_LVL1IACK (*(volatile uint8_t*)(0xFFFFFFE4))
#define INTC_LVL1IACK_VECN0             0x01U
#define INTC_LVL1IACK_VECN1             0x02U
#define INTC_LVL1IACK_VECN2             0x04U
#define INTC_LVL1IACK_VECN3             0x08U
#define INTC_LVL1IACK_VECN4             0x10U
#define INTC_LVL1IACK_VECN5             0x20U
#define INTC_LVL1IACK_VECN6             0x40U
#define INTC_LVL1IACK_VECN              0x7FU
#define INTC_LVL1IACK_VECN_BITNUM       0x00U


/*** INTC_LVL2IACK - INTC Level 2 IACK Register; 0xFFFFFFE8 ***/
#define INTC_LVL2IACK (*(volatile uint8_t*)(0xFFFFFFE8))
#define INTC_LVL2IACK_VECN0             0x01U
#define INTC_LVL2IACK_VECN1             0x02U
#define INTC_LVL2IACK_VECN2             0x04U
#define INTC_LVL2IACK_VECN3             0x08U
#define INTC_LVL2IACK_VECN4             0x10U
#define INTC_LVL2IACK_VECN5             0x20U
#define INTC_LVL2IACK_VECN6             0x40U
#define INTC_LVL2IACK_VECN              0x7FU
#define INTC_LVL2IACK_VECN_BITNUM       0x00U


/*** INTC_LVL3IACK - INTC Level 3 IACK Register; 0xFFFFFFEC ***/
#define INTC_LVL3IACK (*(volatile uint8_t*)(0xFFFFFFEC))
#define INTC_LVL3IACK_VECN0             0x01U
#define INTC_LVL3IACK_VECN1             0x02U
#define INTC_LVL3IACK_VECN2             0x04U
#define INTC_LVL3IACK_VECN3             0x08U
#define INTC_LVL3IACK_VECN4             0x10U
#define INTC_LVL3IACK_VECN5             0x20U
#define INTC_LVL3IACK_VECN6             0x40U
#define INTC_LVL3IACK_VECN              0x7FU
#define INTC_LVL3IACK_VECN_BITNUM       0x00U


/*** INTC_LVL4IACK - INTC Level 4 IACK Register; 0xFFFFFFF0 ***/
#define INTC_LVL4IACK (*(volatile uint8_t*)(0xFFFFFFF0))
#define INTC_LVL4IACK_VECN0             0x01U
#define INTC_LVL4IACK_VECN1             0x02U
#define INTC_LVL4IACK_VECN2             0x04U
#define INTC_LVL4IACK_VECN3             0x08U
#define INTC_LVL4IACK_VECN4             0x10U
#define INTC_LVL4IACK_VECN5             0x20U
#define INTC_LVL4IACK_VECN6             0x40U
#define INTC_LVL4IACK_VECN              0x7FU
#define INTC_LVL4IACK_VECN_BITNUM       0x00U


/*** INTC_LVL5IACK - INTC Level 5 IACK Register; 0xFFFFFFF4 ***/
#define INTC_LVL5IACK (*(volatile uint8_t*)(0xFFFFFFF4))
#define INTC_LVL5IACK_VECN0             0x01U
#define INTC_LVL5IACK_VECN1             0x02U
#define INTC_LVL5IACK_VECN2             0x04U
#define INTC_LVL5IACK_VECN3             0x08U
#define INTC_LVL5IACK_VECN4             0x10U
#define INTC_LVL5IACK_VECN5             0x20U
#define INTC_LVL5IACK_VECN6             0x40U
#define INTC_LVL5IACK_VECN              0x7FU
#define INTC_LVL5IACK_VECN_BITNUM       0x00U


/*** INTC_LVL6IACK - INTC Level 6 IACK Register; 0xFFFFFFF8 ***/
#define INTC_LVL6IACK (*(volatile uint8_t*)(0xFFFFFFF8))
#define INTC_LVL6IACK_VECN0             0x01U
#define INTC_LVL6IACK_VECN1             0x02U
#define INTC_LVL6IACK_VECN2             0x04U
#define INTC_LVL6IACK_VECN3             0x08U
#define INTC_LVL6IACK_VECN4             0x10U
#define INTC_LVL6IACK_VECN5             0x20U
#define INTC_LVL6IACK_VECN6             0x40U
#define INTC_LVL6IACK_VECN              0x7FU
#define INTC_LVL6IACK_VECN_BITNUM       0x00U


/*** INTC_LVL7IACK - INTC Level 7 IACK Register; 0xFFFFFFFC ***/
#define INTC_LVL7IACK (*(volatile uint8_t*)(0xFFFFFFFC))
#define INTC_LVL7IACK_VECN0             0x01U
#define INTC_LVL7IACK_VECN1             0x02U
#define INTC_LVL7IACK_VECN2             0x04U
#define INTC_LVL7IACK_VECN3             0x08U
#define INTC_LVL7IACK_VECN4             0x10U
#define INTC_LVL7IACK_VECN5             0x20U
#define INTC_LVL7IACK_VECN6             0x40U
#define INTC_LVL7IACK_VECN              0x7FU
#define INTC_LVL7IACK_VECN_BITNUM       0x00U


#endif //_IO_MAP_H
